AWSTemplateFormatVersion: 2010-09-09
Description: Creates a Backup Policy and Management Account Vault w/ Vault Lock Configuration

Resources:
  BackupPolicy:
    Type: AWS::Organizations::Policy
    Properties:
      TargetIds: 123456789012
      Type: BACKUP_POLICY
      Name: BackupPolicy01
      Content: >-
        {
            "plans": {
                "PII_Backup_Plan": {
                    "regions": {
                        "@@assign": "us-east-1"
                    },
                    "rules": {
                        "My_Hourly_Rule": {
                            "schedule_expression": {
                                "@@assign": "cron(0 5 ? * * *)"
                            },
                            "start_backup_window_minutes": {
                                "@@assign": "60"
                            },
                            "complete_backup_window_minutes": {
                                "@@assign": "604800"
                            },
                            "enable_continuous_backup": {
                                "@@assign": true
                            },
                            "target_backup_vault_name": {
                                "@@assign": "Vault01"
                            }
                        },
                        "lifecycle": {
                            "delete_after_days": {
                                "@@assign": "8"
                            }
                        }
                    }
                },
                "selections": {
                    "tags": {
                        "ResourceAssignment01": {
                            "iam_role_arn": {
                                "@@assign": "arn:aws:iam::$account:role/MyIamRole"
                            },
                            "tag_key": {
                                "@@assign": "backup"
                            },
                            "tag_value": {
                                "@@assign": "yes"
                            }
                        }
                    }
                }
            }
        }

  BackupVault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: Vault01
      LockConfiguration:
        MaxRetentionDays: 14
        MinRetentionDays: 7
      Notifications:
        BackupVaultEvents: 
            - BACKUP_JOB_COMPLETED
        SNSTopicArn: arn:aws:sns:us-east-1:123456789012:topic01