AWSTemplateFormatVersion: 2010-09-09
Description: Creates a Member Account Vault w/ Vault Lock Configuration

Resources:
  BackupVault:
    Type: AWS::Backup::BackupVault
    Properties:
      BackupVaultName: Vault01
      LockConfiguration:
        MaxRetentionDays: 14
        MinRetentionDays: 7
      Notifications:
        BackupVaultEvents: 
            - BACKUP_JOB_COMPLETED
        SNSTopicArn: arn:aws:sns:us-east-1:123456789012:topic01

  SNSTopic:
    Type: AWS::SNS::Topic
    Properties: 
      ContentBasedDeduplication: Boolean
      DataProtectionPolicy: Json
      DisplayName: MemberAccountTopic
      Subscription: 
        - Endpoint: email@email.com
          Protocol: Email
      TopicName: MemberAccountTopic

  EbsVolume:
    Type: AWS::EC2::Volume
    Properties: 
        Size: 1
        VolumeType: gp2
        AvailabilityZone: us-east-1a
        Tags:
         - Key: "backup"
           Value: "yes"